apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-elyra
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-elyra
  template:
    metadata:
      labels:
        app: jupyter-elyra
    spec:
      containers:
      - name: jupyter
        image: dockerdoktor/jupyter-with-minio:latest
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTERLAB_S3_ENDPOINT
          value: "http://192.168.0.16:9000"        
        - name: JUPYTERLAB_S3_ACCESS_KEY_ID
          value: "hOyUl9puTkI7c9Sf"
        - name: JUPYTERLAB_S3_SECRET_ACCESS_KEY
          value: "fQAehlGU82lyOEiuOHnD0e3oassH1kex"        
        volumeMounts:
        - name: jupyter-volume
          mountPath: /home/jovyan/work
      - name: elyra
        image: elyra/elyra:latest
        ports:
        - containerPort: 8889
        volumeMounts:
        - name: jupyter-volume
          mountPath: /mnt/data/elyra
      volumes:
      - name: jupyter-volume
        persistentVolumeClaim:
          claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-elyra-service
spec:
  type: NodePort
  selector:
    app: jupyter-elyra
  ports:
  - name: jupyter-port
    port: 8888
    targetPort: 8888
    nodePort: 30001    
  - name: elyra-port
    port: 8889
    targetPort: 8889
    nodePort: 30002
