apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-elyra
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-elyra
  template:
    metadata:
      labels:
        app: jupyter-elyra
    spec:
      containers:
      - name: jupyter
        image: dockerdoktor/jupyter-with-minio:latest
        ports:
        - containerPort: 8888
        env:
        - name: AWS_S3_ENDPOINT
          value: "http://localhost:9090"        
        - name: AWS_ACCESS_KEY_ID
          value: "A9vtokrUJrS4Hejp"
        - name: AWS_SECRET_ACCESS_KEY
          value: "cX3bLkCBZtqgUwTuChKca4TSYUXJWJJx"
        - name: AWS_S3_REGION
          value: "fadermodemet"
        volumeMounts:
        - name: jupyter-volume
          mountPath: /home/jovyan/work
      - name: elyra
        image: elyra/elyra:latest
        ports:
        - containerPort: 8889
        volumeMounts:
        - name: jupyter-volume
          mountPath: /mnt/data/elyra
      volumes:
      - name: jupyter-volume
        persistentVolumeClaim:
          claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-elyra-service
spec:
  type: NodePort
  selector:
    app: jupyter-elyra
  ports:
  - name: jupyter-port
    port: 8888
    targetPort: 8888    
  - name: elyra-port
    port: 8889
    targetPort: 8889
